name: everaldo
favicon: null
layout_spectrum: 0.935434193816036
typography_spectrum: 0.9512190683744848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7116008442826569
  lightness: 0.2948125477414578
  saturation: 0.4362509581260383
  rhythmicContrast: 0.6465963628143072
purpose: []
